# Generated by Django 5.0.2 on 2024-02-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("amount", models.FloatField()),
                ("category", models.CharField(max_length=200)),
                ("timestamp", models.DateField(auto_now=True)),
            ],
        ),
    ]
