# Generated by Django 5.0.2 on 2024-02-16 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myexpensetracker", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="category",
            new_name="item",
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="name",
            new_name="type",
        ),
    ]
