# Generated by Django 5.0.2 on 2024-02-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myexpensetracker", "0002_rename_category_expense_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
