# Generated by Django 5.0.2 on 2024-02-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myexpensetracker", "0003_alter_expense_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=200)),
                ("item", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("type", models.CharField(max_length=200)),
                ("timestamp", models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Expense",
        ),
    ]
